# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/pi/New Vision"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/pi/New Vision"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/pi/New Vision/CMakeFiles" "/home/pi/New Vision/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/pi/New Vision/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NewVision

# Build rule for target.
NewVision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NewVision
.PHONY : NewVision

# fast build rule for target.
NewVision/fast:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/build
.PHONY : NewVision/fast

http/server/connection.o: http/server/connection.cpp.o

.PHONY : http/server/connection.o

# target to build an object file
http/server/connection.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/connection.cpp.o
.PHONY : http/server/connection.cpp.o

http/server/connection.i: http/server/connection.cpp.i

.PHONY : http/server/connection.i

# target to preprocess a source file
http/server/connection.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/connection.cpp.i
.PHONY : http/server/connection.cpp.i

http/server/connection.s: http/server/connection.cpp.s

.PHONY : http/server/connection.s

# target to generate assembly for a file
http/server/connection.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/connection.cpp.s
.PHONY : http/server/connection.cpp.s

http/server/connection_manager.o: http/server/connection_manager.cpp.o

.PHONY : http/server/connection_manager.o

# target to build an object file
http/server/connection_manager.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/connection_manager.cpp.o
.PHONY : http/server/connection_manager.cpp.o

http/server/connection_manager.i: http/server/connection_manager.cpp.i

.PHONY : http/server/connection_manager.i

# target to preprocess a source file
http/server/connection_manager.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/connection_manager.cpp.i
.PHONY : http/server/connection_manager.cpp.i

http/server/connection_manager.s: http/server/connection_manager.cpp.s

.PHONY : http/server/connection_manager.s

# target to generate assembly for a file
http/server/connection_manager.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/connection_manager.cpp.s
.PHONY : http/server/connection_manager.cpp.s

http/server/mime_types.o: http/server/mime_types.cpp.o

.PHONY : http/server/mime_types.o

# target to build an object file
http/server/mime_types.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/mime_types.cpp.o
.PHONY : http/server/mime_types.cpp.o

http/server/mime_types.i: http/server/mime_types.cpp.i

.PHONY : http/server/mime_types.i

# target to preprocess a source file
http/server/mime_types.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/mime_types.cpp.i
.PHONY : http/server/mime_types.cpp.i

http/server/mime_types.s: http/server/mime_types.cpp.s

.PHONY : http/server/mime_types.s

# target to generate assembly for a file
http/server/mime_types.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/mime_types.cpp.s
.PHONY : http/server/mime_types.cpp.s

http/server/reply.o: http/server/reply.cpp.o

.PHONY : http/server/reply.o

# target to build an object file
http/server/reply.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/reply.cpp.o
.PHONY : http/server/reply.cpp.o

http/server/reply.i: http/server/reply.cpp.i

.PHONY : http/server/reply.i

# target to preprocess a source file
http/server/reply.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/reply.cpp.i
.PHONY : http/server/reply.cpp.i

http/server/reply.s: http/server/reply.cpp.s

.PHONY : http/server/reply.s

# target to generate assembly for a file
http/server/reply.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/reply.cpp.s
.PHONY : http/server/reply.cpp.s

http/server/request_handler.o: http/server/request_handler.cpp.o

.PHONY : http/server/request_handler.o

# target to build an object file
http/server/request_handler.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/request_handler.cpp.o
.PHONY : http/server/request_handler.cpp.o

http/server/request_handler.i: http/server/request_handler.cpp.i

.PHONY : http/server/request_handler.i

# target to preprocess a source file
http/server/request_handler.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/request_handler.cpp.i
.PHONY : http/server/request_handler.cpp.i

http/server/request_handler.s: http/server/request_handler.cpp.s

.PHONY : http/server/request_handler.s

# target to generate assembly for a file
http/server/request_handler.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/request_handler.cpp.s
.PHONY : http/server/request_handler.cpp.s

http/server/request_parser.o: http/server/request_parser.cpp.o

.PHONY : http/server/request_parser.o

# target to build an object file
http/server/request_parser.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/request_parser.cpp.o
.PHONY : http/server/request_parser.cpp.o

http/server/request_parser.i: http/server/request_parser.cpp.i

.PHONY : http/server/request_parser.i

# target to preprocess a source file
http/server/request_parser.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/request_parser.cpp.i
.PHONY : http/server/request_parser.cpp.i

http/server/request_parser.s: http/server/request_parser.cpp.s

.PHONY : http/server/request_parser.s

# target to generate assembly for a file
http/server/request_parser.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/request_parser.cpp.s
.PHONY : http/server/request_parser.cpp.s

http/server/server.o: http/server/server.cpp.o

.PHONY : http/server/server.o

# target to build an object file
http/server/server.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/server.cpp.o
.PHONY : http/server/server.cpp.o

http/server/server.i: http/server/server.cpp.i

.PHONY : http/server/server.i

# target to preprocess a source file
http/server/server.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/server.cpp.i
.PHONY : http/server/server.cpp.i

http/server/server.s: http/server/server.cpp.s

.PHONY : http/server/server.s

# target to generate assembly for a file
http/server/server.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/http/server/server.cpp.s
.PHONY : http/server/server.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/main.cpp.s
.PHONY : main.cpp.s

opencv-code/cap_gstreamer.o: opencv-code/cap_gstreamer.cpp.o

.PHONY : opencv-code/cap_gstreamer.o

# target to build an object file
opencv-code/cap_gstreamer.cpp.o:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/opencv-code/cap_gstreamer.cpp.o
.PHONY : opencv-code/cap_gstreamer.cpp.o

opencv-code/cap_gstreamer.i: opencv-code/cap_gstreamer.cpp.i

.PHONY : opencv-code/cap_gstreamer.i

# target to preprocess a source file
opencv-code/cap_gstreamer.cpp.i:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/opencv-code/cap_gstreamer.cpp.i
.PHONY : opencv-code/cap_gstreamer.cpp.i

opencv-code/cap_gstreamer.s: opencv-code/cap_gstreamer.cpp.s

.PHONY : opencv-code/cap_gstreamer.s

# target to generate assembly for a file
opencv-code/cap_gstreamer.cpp.s:
	$(MAKE) -f CMakeFiles/NewVision.dir/build.make CMakeFiles/NewVision.dir/opencv-code/cap_gstreamer.cpp.s
.PHONY : opencv-code/cap_gstreamer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... NewVision"
	@echo "... edit_cache"
	@echo "... http/server/connection.o"
	@echo "... http/server/connection.i"
	@echo "... http/server/connection.s"
	@echo "... http/server/connection_manager.o"
	@echo "... http/server/connection_manager.i"
	@echo "... http/server/connection_manager.s"
	@echo "... http/server/mime_types.o"
	@echo "... http/server/mime_types.i"
	@echo "... http/server/mime_types.s"
	@echo "... http/server/reply.o"
	@echo "... http/server/reply.i"
	@echo "... http/server/reply.s"
	@echo "... http/server/request_handler.o"
	@echo "... http/server/request_handler.i"
	@echo "... http/server/request_handler.s"
	@echo "... http/server/request_parser.o"
	@echo "... http/server/request_parser.i"
	@echo "... http/server/request_parser.s"
	@echo "... http/server/server.o"
	@echo "... http/server/server.i"
	@echo "... http/server/server.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... opencv-code/cap_gstreamer.o"
	@echo "... opencv-code/cap_gstreamer.i"
	@echo "... opencv-code/cap_gstreamer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

